const donnees = [
{ titre:'NGC 1023',constellation:'Persée',image:'images/NGC1023-a.jpg', nom:'', type:'Galaxie ',mag:' 9,5', saison :'automne'},
{ titre:'NGC 1232',constellation:'Eridan',image:'images/NGC1232-a.jpg', nom:'', type:'Galaxie ',mag:' 9,9', saison :'automne'},
{ titre:'NGC 1491',constellation:'Persée',image:'images/NGC1491-a.jpg', nom:'', type:'Nébuleuse ',mag:' ?', saison :'automne'},
{ titre:'NGC 1501',constellation:'la Girafe',image:'images/NGC1501-a.jpg', nom:'Nébuleuse de l\’Huître', type:'Nébuleuse planétaire ',mag:' 12', saison :'circumpolaires'},
{ titre:'NGC 1514',constellation:'le Taureau',image:'images/NGC1514-a.jpg', nom:'Nébuleuse de la Rosée', type:'Nébuleuse planétaire ',mag:' 9,4', saison :'hiver'},
{ titre:'NGC 1535',constellation:'Eridan',image:'images/NGC1535-a.jpg', nom:'L\'Œil de Cléopâtre', type:'Nébuleuse planétaire ',mag:' 9,6', saison :'automne'},
{ titre:'NGC 1788',constellation:'Orion',image:'images/NGC1788-a.jpg', nom:'', type:'Nébuleuse ',mag:' ?', saison :'hiver'},
{ titre:'NGC 185',constellation:'Cassiopée',image:'images/NGC185-a.jpg', nom:'', type:'Galaxie ',mag:' 11,2', saison :'circumpolaires'},
{ titre:'NGC 1907',constellation:'le Cocher',image:'images/NGC1907-a.jpg', nom:'', type:'Amas ouvert ',mag:' 8,2', saison :'hiver'},
{ titre:'NGC 1931',constellation:'le Cocher',image:'images/NGC1931-a.jpg', nom:'', type:'Nébuleuse ',mag:' 10,1', saison :'hiver'},
{ titre:'NGC 1973',constellation:'Orion',image:'images/NGC1973-a.jpg', nom:'Nébuleuse du Coureur', type:'Nébuleuse ',mag:' 7', saison :'hiver'},
{ titre:'NGC 2022',constellation:'Orion',image:'images/NGC2022-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 12,8', saison :'hiver'},
{ titre:'NGC 2024',constellation:'Orion',image:'images/NGC2024-a.jpg', nom:'Nébuleuse de la Flamme', type:'Nébuleuse ',mag:' ?', saison :'hiver'},
{ titre:'NGC 2158',constellation:'les Gémeaux',image:'images/NGC2158-a.jpg', nom:'', type:'Amas ouvert ',mag:' 8,6', saison :'hiver'},
{ titre:'NGC 2194',constellation:'Orion',image:'images/NGC2194-a.jpg', nom:'', type:'Amas ouvert ',mag:' 8,5', saison :'hiver'},
{ titre:'NGC 2237',constellation:'la Licorne',image:'images/NGC2237-a.jpg', nom:'Nébuleuse de la Rosette', type:'Nébuleuse ',mag:' 4,8', saison :'hiver'},
{ titre:'NGC 2261',constellation:'la Licorne',image:'images/NGC2261-a.jpg', nom:'Nébuleuse variable de Hubble', type:'Nébuleuse ',mag:' 10', saison :'hiver'},
{ titre:'NGC 2359',constellation:'le Grand Chien',image:'images/NGC2359-a.jpg', nom:'Le Casque de Thor', type:'Nébuleuse ',mag:' ?', saison :'hiver'},
{ titre:'NGC 2371',constellation:'les Gémeaux',image:'images/NGC2371-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 11,2', saison :'hiver'},
{ titre:'NGC 2392',constellation:'les Gémeaux',image:'images/NGC2392-a.jpg', nom:'Nébuleuse de l\'Esquimau', type:'Nébuleuse planétaire ',mag:' 9', saison :'hiver'},
{ titre:'NGC 2403',constellation:'la Girafe',image:'images/NGC2403-a.jpg', nom:'', type:'Galaxie ',mag:' 8,5', saison :'circumpolaires'},
{ titre:'NGC 2438',constellation:'la Poupe',image:'images/NGC2438-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 10,8', saison :'hiver'},
{ titre:'NGC 2440',constellation:'la Poupe',image:'images/NGC2440-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 11,8', saison :'hiver'},
{ titre:'NGC 246',constellation:'la Baleine',image:'images/NGC246-a.jpg', nom:'Nébuleuse du Crâne', type:'Nébuleuse planétaire ',mag:' 8', saison :'automne'},
{ titre:'NGC 253',constellation:'le Sculpteur',image:'images/NGC253-a.jpg', nom:'La Galaxie du Sculpteur', type:'Galaxie ',mag:' 7,5', saison :'automne'},
{ titre:'NGC 2539',constellation:'la Poupe',image:'images/NGC2539-a.jpg', nom:'', type:'Amas ouvert ',mag:' 6,5', saison :'hiver'},
{ titre:'NGC 2655',constellation:'la Girafe',image:'images/NGC2655-a.jpg', nom:'', type:'Galaxie ',mag:' 10', saison :'circumpolaires'},
{ titre:'NGC 2683',constellation:'le Lynx',image:'images/NGC2683-a.jpg', nom:'', type:'Galaxie ',mag:' 9,7', saison :'hiver'},
{ titre:'NGC 281',constellation:'Cassiopée',image:'images/NGC281-a.jpg', nom:'Nébuleuse Pacman', type:'Nébuleuse ',mag:' 7', saison :'circumpolaires'},
{ titre:'NGC 2841',constellation:'la Grande Ourse',image:'images/NGC2841-a.jpg', nom:'', type:'Galaxie ',mag:' 9,2', saison :'circumpolaires'},
{ titre:'NGC 2903',constellation:'le Lion',image:'images/NGC2903-a.jpg', nom:'', type:'Galaxie ',mag:' 9', saison :'printemps'},
{ titre:'NGC 3003',constellation:'le Petit Lion',image:'images/NGC3003-a.jpg', nom:'', type:'Galaxie ',mag:' 11,9', saison :'printemps'},
{ titre:'NGC 3077',constellation:'la Grande Ourse',image:'images/NGC3077-a.jpg', nom:'', type:'Galaxie ',mag:' 9.9', saison :'circumpolaires'},
{ titre:'NGC 3079',constellation:'la Grande Ourse',image:'images/NGC3079-a.jpg', nom:'', type:'Galaxie ',mag:' 10.9', saison :'circumpolaires'},
{ titre:'NGC 3115',constellation:'le Sextant',image:'images/NGC3115-a.jpg', nom:'La Galaxie du Fuseau', type:'Galaxie ',mag:' 9,1', saison :'printemps'},
{ titre:'NGC 3184',constellation:'la Grande Ourse',image:'images/NGC3184-a.jpg', nom:'', type:'Galaxie ',mag:' 9,8', saison :'circumpolaires'},
{ titre:'NGC 3242',constellation:'l\'Hydre Femelle',image:'images/NGC3242-a.jpg', nom:'Le Fantôme de Jupiter', type:'Nébuleuse planétaire ',mag:' 8,6', saison :'été'},
{ titre:'NGC 3344',constellation:'le Petit Lion',image:'images/NGC3344-a.jpg', nom:'', type:'Galaxie ',mag:' 9,9', saison :'printemps'},
{ titre:'NGC 3384',constellation:'le Lion',image:'images/NGC3384-a.jpg', nom:'', type:'Galaxie ',mag:' 9,9', saison :'printemps'},
{ titre:'NGC 3432',constellation:'le Petit Lion',image:'images/NGC3432-a.jpg', nom:'', type:'Galaxie ',mag:' 11,3', saison :'printemps'},
{ titre:'NGC 3521',constellation:'le Lion',image:'images/NGC3521-a.jpg', nom:'', type:'Galaxie ',mag:' 9,8', saison :'printemps'},
{ titre:'NGC 3607',constellation:'le Lion',image:'images/NGC3607-a.jpg', nom:'', type:'Galaxie ',mag:' 9,9', saison :'printemps'},
{ titre:'NGC 3628',constellation:'le Lion',image:'images/NGC3628-a.jpg', nom:'Trio du Lion', type:'Galaxie ',mag:' 9,5', saison :'printemps'},
{ titre:'NGC 3675',constellation:'la Grande Ourse',image:'images/NGC3675-a.jpg', nom:'', type:'Galaxie ',mag:' 10,2', saison :'circumpolaires'},
{ titre:'NGC 3877',constellation:'la Grande Ourse',image:'images/NGC3877-a.jpg', nom:'', type:'Galaxie ',mag:' 11', saison :'circumpolaires'},
{ titre:'NGC 3941',constellation:'la Grande Ourse',image:'images/NGC3941-a.jpg', nom:'', type:'Galaxie ',mag:' 10,3', saison :'circumpolaires'},
{ titre:'NGC 40',constellation:'le Dragon',image:'images/NGC40-a.jpg', nom:'Nébuleuse Nœud Papillon', type:'Nébuleuse planétaire ',mag:' 10,7', saison :'circumpolaires'},
{ titre:'NGC 4026',constellation:'la Grande Ourse',image:'images/NGC4026-a.jpg', nom:'', type:'Galaxie ',mag:' 10,8', saison :'circumpolaires'},
{ titre:'NGC 4038',constellation:'le Corbeau',image:'images/NGC4038-a.jpg', nom:'Galaxies des Antennes', type:'Galaxies ',mag:' 10,3', saison :'printemps'},
{ titre:'NGC 4088',constellation:'la Grande Ourse',image:'images/NGC4088-a.jpg', nom:'', type:'Galaxie ',mag:' 10,6', saison :'circumpolaires'},
{ titre:'NGC 4111',constellation:'les Chiens de Chasse',image:'images/NGC4111-a.jpg', nom:'', type:'Galaxie ',mag:' 10,7', saison :'printemps'},
{ titre:'NGC 4157',constellation:'la Grande Ourse',image:'images/NGC4157-a.jpg', nom:'', type:'Galaxie ',mag:' 11,4', saison :'circumpolaires'},
{ titre:'NGC 4214',constellation:'les Chiens de Chasse',image:'images/NGC4214-a.jpg', nom:'', type:'Galaxie ',mag:' 9,8', saison :'printemps'},
{ titre:'NGC 4216',constellation:'la Vierge',image:'images/NGC4216-a.jpg', nom:'La Galaxie Soucoupe Volante', type:'Galaxie ',mag:' 10', saison :'printemps'},
{ titre:'NGC 4244',constellation:'les Chiens de Chasse',image:'images/NGC4244-a.jpg', nom:'', type:'Galaxie ',mag:' 10,4', saison :'printemps'},
{ titre:'NGC 4274',constellation:'la Chevelure de Bérénice',image:'images/NGC4274-a.jpg', nom:'', type:'Galaxie ',mag:' 10,1', saison :'printemps'},
{ titre:'NGC 4361',constellation:'le Corbeau',image:'images/NGC4361-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 10,3', saison :'printemps'},
{ titre:'NGC 4388',constellation:'la Vierge',image:'images/NGC4388-a.jpg', nom:'Galaxie', type:'Galaxie ',mag:' 11', saison :'printemps'},
{ titre:'NGC 4414',constellation:'la Chevelure de Bérénice',image:'images/NGC4414-a.jpg', nom:'', type:'Galaxie ',mag:' 10,1', saison :'printemps'},
{ titre:'NGC 4438',constellation:'la Vierge',image:'images/NGC4438-a.jpg', nom:'La Galaxie des Yeux', type:'Galaxie ',mag:' 10,1', saison :'printemps'},
{ titre:'NGC 4449',constellation:'les Chiens de Chasse',image:'images/NGC4449-a.jpg', nom:'', type:'Galaxie ',mag:' 9,6', saison :'printemps'},
{ titre:'NGC 4490',constellation:'les Chiens de Chasse',image:'images/NGC4490-a.jpg', nom:'La Galaxie du Cocon', type:'Galaxie ',mag:' 9,8', saison :'printemps'},
{ titre:'NGC 4494',constellation:'la Chevelure de Bérénice',image:'images/NGC4494-a.jpg', nom:'', type:'Galaxie ',mag:' 9,8', saison :'printemps'},
{ titre:'NGC 4517',constellation:'la Vierge',image:'images/NGC4517-a.jpg', nom:'', type:'Galaxie ',mag:' 10,4', saison :'printemps'},
{ titre:'NGC 4526',constellation:'la Vierge',image:'images/NGC4526-a.jpg', nom:'', type:'Galaxie ',mag:' 9,7', saison :'printemps'},
{ titre:'NGC 4535',constellation:'la Vierge',image:'images/NGC4535-a.jpg', nom:'La Galaxie Perdue', type:'Galaxie ',mag:' 10', saison :'printemps'},
{ titre:'NGC 4559',constellation:'la Chevelure de Bérénice',image:'images/NGC4559-a.jpg', nom:'', type:'Galaxie ',mag:' 10', saison :'printemps'},
{ titre:'NGC 4565',constellation:'la Chevelure de Bérénice',image:'images/NGC4565-a.jpg', nom:'La Galaxie de l\'Aiguille', type:'Galaxie ',mag:' 9,6', saison :'printemps'},
{ titre:'NGC 4567',constellation:'la Vierge',image:'images/NGC4567-a.jpg', nom:'Les Jumeaux Siamois', type:'Galaxies ',mag:' 11,3 et 10,8', saison :'printemps'},
{ titre:'NGC 457',constellation:'Cassiopée',image:'images/NGC457-a.jpg', nom:'Amas du Hibou', type:'Amas ouvert ',mag:' 6,4', saison :'circumpolaires'},
{ titre:'NGC 4605',constellation:'la Grande Ourse',image:'images/NGC4605-a.jpg', nom:'', type:'Galaxie ',mag:' 10,3', saison :'circumpolaires'},
{ titre:'NGC 4631',constellation:'les Chiens de Chasse',image:'images/NGC4631-a.jpg', nom:'La Galaxie de la Baleine', type:'Galaxie ',mag:' 9,1', saison :'printemps'},
{ titre:'NGC 4656',constellation:'les Chiens de Chasse',image:'images/NGC4656-a.jpg', nom:'La Crosse de Hockey', type:'Galaxie ',mag:' 10,5', saison :'printemps'},
{ titre:'NGC 4699',constellation:'la Vierge',image:'images/NGC4699-a.jpg', nom:'', type:'Galaxie ',mag:' 9,5', saison :'printemps'},
{ titre:'NGC 4725',constellation:'la Chevelure de Bérénice',image:'images/NGC4725-a.jpg', nom:'', type:'Galaxie ',mag:' 9,3', saison :'printemps'},
{ titre:'NGC 4762',constellation:'la Vierge',image:'images/NGC4762-a.jpg', nom:'Le Trait de Lumière', type:'Galaxie ',mag:' 10,3', saison :'printemps'},
{ titre:'NGC 5005',constellation:'les Chiens de Chasse',image:'images/NGC5005-a.jpg', nom:'', type:'Galaxie ',mag:' 9,8', saison :'printemps'},
{ titre:'NGC 5033',constellation:'les Chiens de Chasse',image:'images/NGC5033-a.jpg', nom:'', type:'Galaxie ',mag:' 10,1', saison :'printemps'},
{ titre:'NGC 5466',constellation:'le Bouvier',image:'images/NGC5466-a.jpg', nom:'', type:'Amas globulaire ',mag:' 9,2', saison :'printemps'},
{ titre:'NGC 5746',constellation:'la Vierge',image:'images/NGC5746-a.jpg', nom:'', type:'Galaxie ',mag:' 10,3', saison :'printemps'},
{ titre:'NGC 5907',constellation:'le Dragon',image:'images/NGC5907-a.jpg', nom:'La Galaxie de l\’Écharde', type:'Galaxie ',mag:' 10,4', saison :'circumpolaires'},
{ titre:'NGC 6207',constellation:'Hercule',image:'images/NGC6207-a.jpg', nom:'', type:'Galaxie ',mag:' 11,6', saison :'été'},
{ titre:'NGC 6210',constellation:'Hercule',image:'images/NGC6210-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 9,7', saison :'été'},
{ titre:'NGC 6369',constellation:'Ophiuchus',image:'images/NGC6369-a.jpg', nom:'Nébuleuse du Petit Fantôme', type:'Nébuleuse planétaire ',mag:' 11', saison :'été'},
{ titre:'NGC 6445',constellation:'le Sagittaire',image:'images/NGC6445-a.jpg', nom:'Nébuleuse du Pâté en Croûte', type:'Nébuleuse planétaire ',mag:' 13', saison :'été'},
{ titre:'NGC 6503',constellation:'le Dragon',image:'images/NGC6503-a.jpg', nom:'', type:'Galaxie ',mag:' 10,2', saison :'circumpolaires'},
{ titre:'NGC 6520',constellation:'le Sagittaire',image:'images/NGC6520-a.jpg', nom:'', type:'Amas ouvert ',mag:' 7,6', saison :'été'},
{ titre:'NGC 6543',constellation:'le Dragon',image:'images/NGC6543-a.jpg', nom:'Nébuleuse de L\’Œil de Chat', type:'Nébuleuse planétaire ',mag:' 8,8', saison :'circumpolaires'},
{ titre:'NGC 6572',constellation:'Ophiuchus',image:'images/NGC6572-a.jpg', nom:'Nébuleuse de l\’Émeraude', type:'Nébuleuse planétaire ',mag:' 9', saison :'été'},
{ titre:'NGC 663',constellation:'Cassiopée',image:'images/NGC663-a.jpg', nom:'', type:'Amas ouvert ',mag:' 7,1', saison :'circumpolaires'},
{ titre:'NGC 6633',constellation:'Opiuchus',image:'images/NGC6633-a.jpg', nom:'', type:'Amas ouvert ',mag:' 4,6', saison :'été'},
{ titre:'NGC 6712',constellation:'l\’Ecu',image:'images/NGC6712-a.jpg', nom:'', type:'Amas globulaire ',mag:' 8,2', saison :'été'},
{ titre:'NGC 6781',constellation:'l\’Aigle',image:'images/NGC6781-a.jpg', nom:'Nébuleuse Aquila', type:'Nébuleuse planétaire ',mag:' 12', saison :'été'},
{ titre:'NGC 6802',constellation:'le Petit Renard',image:'images/NGC6802-a.jpg', nom:'', type:'Amas ouvert ',mag:' 8,8', saison :'été'},
{ titre:'NGC 6818',constellation:'le Sagittaire',image:'images/NGC6818-a.jpg', nom:'Nébuleuse du Petit Diamant', type:'Nébuleuse planétaire ',mag:' 9,9', saison :'été'},
{ titre:'NGC 6819',constellation:'le Cygne',image:'images/NGC6819-a.jpg', nom:'', type:'Amas ouvert ',mag:' 7,3', saison :'été'},
{ titre:'NGC 6826',constellation:'le Cygne',image:'images/NGC6826-a.jpg', nom:'Nébuleuse Clignotante', type:'Nébuleuse planétaire ',mag:' 9', saison :'été'},
{ titre:'NGC 6888',constellation:'le Cygne',image:'images/NGC6888-a.jpg', nom:'Nébuleuse du Croissant', type:'Nébuleuse ',mag:' 14', saison :'été'},
{ titre:'NGC 6939',constellation:'Céphée',image:'images/NGC6939-a.jpg', nom:'', type:'Amas ouvert ',mag:' 8', saison :'circumpolaires'},
{ titre:'NGC 6940',constellation:'le Petit Renard',image:'images/NGC6940-a.jpg', nom:'', type:'Amas ouvert ',mag:' 6,3', saison :'été'},
{ titre:'NGC 6946',constellation:'Céphée',image:'images/NGC6946-a.jpg', nom:'La Galaxie du Feu d’Artifice', type:'Galaxie ',mag:' 8,8', saison :'circumpolaires'},
{ titre:'NGC 6960',constellation:'le Cygne',image:'images/NGC6960-a.jpg', nom:'Les Dentelles du Cygne', type:'Nébuleuse ',mag:' 7', saison :'été'},
{ titre:'NGC 7000',constellation:'le Cygne',image:'images/NGC7000-a.jpg', nom:'Nébuleuse América', type:'Nébuleuse ',mag:' 5', saison :'été'},
{ titre:'NGC 7009',constellation:'les Verseaux',image:'images/NGC7009-a.jpg', nom:'Nébuleuse Saturne', type:'Nébuleuse planétaire ',mag:' 8,3', saison :'automne'},
{ titre:'NGC 7027',constellation:'le Cygne',image:'images/NGC7027-a.jpg', nom:'', type:'Nébuleuse planétaire ',mag:' 9,6', saison :'été'},
{ titre:'NGC 7129',constellation:'Céphée',image:'images/NGC7129-a.jpg', nom:'', type:'Nébuleuse ',mag:' 11,5', saison :'circumpolaires'},
{ titre:'NGC 7209',constellation:'le Lézard',image:'images/NGC7209-a.jpg', nom:'', type:'Amas Ouvert ',mag:' 7,7', saison :'circumpolaires'},
{ titre:'NGC 7243',constellation:'le Lézard',image:'images/NGC7243-a.jpg', nom:'', type:'Amas Ouvert ',mag:' 6,4', saison :'circumpolaires'},
{ titre:'NGC 7293',constellation:'les Verseaux',image:'images/NGC7293-a.jpg', nom:'Nébuleuse Hélix', type:'Nébuleuse planétaire ',mag:' 6,5', saison :'automne'},
{ titre:'NGC 7331',constellation:'Pégase',image:'images/NGC7331-a.jpg', nom:'', type:'Galaxie ',mag:' 10', saison :'automne'},
{ titre:'NGC 7635',constellation:'Cassiopée',image:'images/NGC7635-a.jpg', nom:'La Bulle', type:'Nébuleuse ',mag:' 7', saison :'circumpolaires'},
{ titre:'NGC 7662',constellation:'Andromède',image:'images/NGC7662-a.jpg', nom:'Boule de Neige Bleue', type:'Nébuleuse planétaire ',mag:' 9,2', saison :'automne'},
{ titre:'NGC 772',constellation:'le Bélier',image:'images/NGC772-a.jpg', nom:'', type:'Galaxie ',mag:' 10,3', saison :'automne'},
{ titre:'NGC 7789',constellation:'Cassiopée',image:'images/NGC7789-a.jpg', nom:'La Rose de Caroline', type:'Amas ouvert ',mag:' 6,7', saison :'circumpolaires'},
{ titre:'NGC 869',constellation:'Persée',image:'images/NGC869-a.jpg', nom:'Double amas de Persée', type:'Amas ouverts ',mag:' 4,3 et 4,4', saison :'automne'},
{ titre:'NGC 891',constellation:'Andromède',image:'images/NGC891-a.jpg', nom:'', type:'Galaxie ',mag:' 9,9', saison :'automne'},
{ titre:'NGC 936',constellation:'la Baleine',image:'images/NGC936-a.jpg', nom:'', type:'Galaxie ',mag:' 10,1', saison :'automne'},
];