const donnees = [
{ titre:'M52',constellation:'Cassiopée',image:'images/M52-a.jpg', nom:'', type:'amas ouvert',mag:'7,3', saison :'circumpolaires'},
{ titre:'M103',constellation:'Cassiopée',image:'images/M103-a.jpg', nom:'', type:'amas ouvert',mag:'7,4', saison :'circumpolaires'},
{ titre:'NGC281',constellation:'Cassiopée',image:'images/NGC281-a.jpg', nom:'Nébuleuse Pacman', type:'nébuleuse diffuse et amas ouvert',mag:'7,4', saison :'circumpolaires'},
{ titre:'NGC457',constellation:'Cassiopée',image:'images/NGC457-a.jpg', nom:'Amas de la Chouette', type:'amas ouvert',mag:'6,4', saison :'circumpolaires'},
{ titre:'NGC663',constellation:'Cassiopée',image:'images/NGC663-a.jpg', nom:'', type:'amas ouvert',mag:'7,1', saison :'circumpolaires'},
{ titre:'NGC7789',constellation:'Cassiopée',image:'images/NGC7789-a.jpg', nom:'La Rose de Caroline', type:'amas ouvert',mag:'6,7', saison :'circumpolaires'},
{ titre:'NGC7790',constellation:'Cassiopée',image:'images/NGC7790-a.jpg', nom:'', type:'amas ouvert',mag:'8,5', saison :'circumpolaires'},
{ titre:'NGC185',constellation:'Cassiopée',image:'images/NGC185-a.jpg', nom:'', type:'galaxie naine sphéroïdale',mag:'9,2', saison :'circumpolaires'},
{ titre:'NGC147',constellation:'Cassiopée',image:'images/NGC147-a.jpg', nom:'', type:'galaxie naine elliptique',mag:'9,5', saison :'circumpolaires'},
{ titre:'NGC278',constellation:'Cassiopée',image:'images/NGC278-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'10,8', saison :'circumpolaires'},
{ titre:'NGC6939',constellation:'Céphée',image:'images/NGC6939-a.jpg', nom:'', type:'amas ouvert',mag:'7,8', saison :'circumpolaires'},
{ titre:'NGC6946',constellation:'Céphée',image:'images/NGC6946-a.jpg', nom:'Galaxie du feu d\'artifice ou du Moulin', type:'galaxie spirale',mag:'8,8', saison :'circumpolaires'},
{ titre:'NGC2276',constellation:'Céphée',image:'images/NGC2276-a.jpg', nom:'duo avec 2300', type:'galaxie spirale intermédiaire',mag:'11,8', saison :'circumpolaires'},
{ titre:'NGC2300',constellation:'Céphée',image:'images/NGC2300-a.jpg', nom:'duo avec 2276', type:'galaxie lenticulaire',mag:'11,1', saison :'circumpolaires'},
{ titre:'M102',constellation:'Le Dragon',image:'images/M102-a.jpg', nom:'Galaxie du Fuseau', type:'galaxie lenticulaire',mag:'9,9', saison :'circumpolaires'},
{ titre:'NGC5907',constellation:'Le Dragon',image:'images/NGC5907-a.jpg', nom:'Galaxie de l\'Echarde', type:'galaxie spirale',mag:'10,3', saison :'circumpolaires'},
{ titre:'NGC6543',constellation:'Le Dragon',image:'images/NGC6543-a.jpg', nom:'L\'Oeil de Chat', type:'nébuleuse planétaire',mag:'8,3', saison :'circumpolaires'},
{ titre:'NGC5906',constellation:'Le Dragon',image:'images/NGC5906-a.jpg', nom:'', type:'galaxie spirale',mag:'10,3', saison :'circumpolaires'},
{ titre:'NGC5907',constellation:'Le Dragon',image:'images/NGC5907-a.jpg', nom:'', type:'galaxie spirale',mag:'10,3', saison :'circumpolaires'},
{ titre:'NGC6503',constellation:'Le Dragon',image:'images/NGC6503-a.jpg', nom:'', type:'galaxie naine spirale',mag:'10,2', saison :'circumpolaires'},
{ titre:'NGC5985',constellation:'Le Dragon',image:'images/NGC5985-a.jpg', nom:'', type:'galaxie spirale',mag:'11,1', saison :'circumpolaires'},
{ titre:'NGC5982',constellation:'Le Dragon',image:'images/NGC5982-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'11,1', saison :'circumpolaires'},
{ titre:'NGC5879',constellation:'Le Dragon',image:'images/NGC5879-a.jpg', nom:'', type:'galaxie spirale',mag:'11,6', saison :'circumpolaires'},
{ titre:'NGC6643',constellation:'Le Dragon',image:'images/NGC6643-a.jpg', nom:'', type:'galaxie spirale',mag:'11,1', saison :'circumpolaires'},
{ titre:'NGC6340',constellation:'Le Dragon',image:'images/NGC6340-a.jpg', nom:'', type:'galaxie spirale',mag:'11', saison :'circumpolaires'},
{ titre:'NGC6015',constellation:'Le Dragon',image:'images/NGC6015-a.jpg', nom:'', type:'galaxie spirale',mag:'11,1', saison :'circumpolaires'},
{ titre:'NGC6140',constellation:'Le Dragon',image:'images/NGC6140-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,8', saison :'circumpolaires'},
{ titre:'NGC2403',constellation:'La Girafe',image:'images/NGC2403-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'8,5', saison :'circumpolaires'},
{ titre:'NGC2655',constellation:'La Girafe',image:'images/NGC2655-a.jpg', nom:'', type:'galaxie spirale',mag:'10,1', saison :'circumpolaires'},
{ titre:'NGC2336',constellation:'La Girafe',image:'images/NGC2336-a.jpg', nom:'', type:'vaste galaxie spirale intermédiaire',mag:'10,3', saison :'circumpolaires'},
{ titre:'NGC2146',constellation:'La Girafe',image:'images/NGC2146-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,4', saison :'circumpolaires'},
{ titre:'NGC2715',constellation:'La Girafe',image:'images/NGC2715-a.jpg', nom:'', type:'galaxie spirale',mag:'11,6', saison :'circumpolaires'},
{ titre:'NGC2268',constellation:'La Girafe',image:'images/NGC2268-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,8', saison :'circumpolaires'},
{ titre:'M81',constellation:'La Grande Ourse',image:'images/M81-a.jpg', nom:'Galaxie de Bode', type:'galaxie spirale',mag:'6,9', saison :'circumpolaires'},
{ titre:'M82',constellation:'La Grande Ourse',image:'images/M82-a.jpg', nom:'Galaxie du Cigare', type:'galaxie irrég.',mag:'8,4', saison :'circumpolaires'},
{ titre:'M97',constellation:'La Grande Ourse',image:'images/M97-a.jpg', nom:'Nébuleuse du Hibou ou de la Chouette)', type:'nébuleuse planétaire',mag:'9,9', saison :'circumpolaires'},
{ titre:'M101',constellation:'La Grande Ourse',image:'images/M101-a.jpg', nom:'Pinwheel', type:'galaxie spirale',mag:'7,9', saison :'circumpolaires'},
{ titre:'M108',constellation:'La Grande Ourse',image:'images/M108-a.jpg', nom:'Planche de surf', type:'galaxie spirale',mag:'10', saison :'circumpolaires'},
{ titre:'M109',constellation:'La Grande Ourse',image:'images/M109-a.jpg', nom:'Galaxie de l\'aspirateur', type:'galaxie spirale barrée',mag:'9,8', saison :'circumpolaires'},
{ titre:'NGC2768',constellation:'La Grande Ourse',image:'images/NGC2768-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'9,9', saison :'circumpolaires'},
{ titre:'NGC2841',constellation:'La Grande Ourse',image:'images/NGC2841-a.jpg', nom:'', type:'galaxie spirale',mag:'9,2', saison :'circumpolaires'},
{ titre:'NGC2681',constellation:'La Grande Ourse',image:'images/NGC2681-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'10,3', saison :'circumpolaires'},
{ titre:'NGC3184',constellation:'La Grande Ourse',image:'images/NGC3184-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'9,8', saison :'circumpolaires'},
{ titre:'NGC2787',constellation:'La Grande Ourse',image:'images/NGC2787-a.jpg', nom:'', type:'galaxie lenticulaire barrée',mag:'10,8', saison :'circumpolaires'},
{ titre:'NGC3077',constellation:'La Grande Ourse',image:'images/NGC3077-a.jpg', nom:'', type:'galaxie irrégulière',mag:'9,9', saison :'circumpolaires'},
{ titre:'NGC2950',constellation:'La Grande Ourse',image:'images/NGC2950-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'9,9', saison :'circumpolaires'},
{ titre:'NGC3079',constellation:'La Grande Ourse',image:'images/NGC3079-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,9', saison :'circumpolaires'},
{ titre:'NGC4088',constellation:'La Grande Ourse',image:'images/NGC4088-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,2', saison :'circumpolaires'},
{ titre:'NGC3665',constellation:'La Grande Ourse',image:'images/NGC3665-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'10,7', saison :'circumpolaires'},
{ titre:'NGC3877',constellation:'La Grande Ourse',image:'images/NGC3877-a.jpg', nom:'', type:'galaxie spirale',mag:'12,1', saison :'circumpolaires'},
{ titre:'NGC3726',constellation:'La Grande Ourse',image:'images/NGC3726-a.jpg', nom:'', type:'galaxie spirale',mag:'10,2', saison :'circumpolaires'},
{ titre:'NGC4026',constellation:'La Grande Ourse',image:'images/NGC4026-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'10,7', saison :'circumpolaires'},
{ titre:'NGC3941',constellation:'La Grande Ourse',image:'images/NGC3941-a.jpg', nom:'', type:'galaxie lenticulaire barrée',mag:'10,3', saison :'circumpolaires'},
{ titre:'NGC4605',constellation:'La Grande Ourse',image:'images/NGC4605-a.jpg', nom:'', type:'galaxie spirale',mag:'10,7', saison :'circumpolaires'},
{ titre:'NGC4157',constellation:'La Grande Ourse',image:'images/NGC4157-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,7', saison :'circumpolaires'},
{ titre:'NGC3718',constellation:'La Grande Ourse',image:'images/NGC3718-a.jpg', nom:'', type:'galaxies spirales en interaction',mag:'10,8', saison :'circumpolaires'},
{ titre:'NGC3729',constellation:'La Grande Ourse',image:'images/NGC3729-a.jpg', nom:'', type:'galaxies spirales en interaction',mag:'11,4', saison :'circumpolaires'},
{ titre:'NGC3738',constellation:'La Grande Ourse',image:'images/NGC3738-a.jpg', nom:'', type:'galaxie naine',mag:'11,7', saison :'circumpolaires'},
{ titre:'NGC3756',constellation:'La Grande Ourse',image:'images/NGC3756-a.jpg', nom:'', type:'galaxie spirale',mag:'11,8', saison :'circumpolaires'},
{ titre:'NGC6217',constellation:'La Petite Ourse',image:'images/NGC6217-a.jpg', nom:'', type:'galaxie',mag:'11,2', saison :'circumpolaires'},
{ titre:'M31',constellation:'Andromède',image:'images/M31-a.jpg', nom:'Galaxie d\'Andromède', type:'galaxie spirale',mag:'3,4', saison :'automne'},
{ titre:'M32',constellation:'Andromède',image:'images/M32-a.jpg', nom:'(galaxie Satellite de M31)', type:'galaxie elliptique',mag:'8,1', saison :'automne'},
{ titre:'M110',constellation:'Andromède',image:'images/M110-a.jpg', nom:'(galaxie Satellite de M31)', type:'galaxie elliptique',mag:'8,5', saison :'automne'},
{ titre:'NGC7662',constellation:'Andromède',image:'images/NGC7662-a.jpg', nom:'Boule de neige bleue', type:'nébuleuse planétaire',mag:'8,6', saison :'automne'},
{ titre:'NGC752',constellation:'Andromède',image:'images/NGC752-a.jpg', nom:'', type:'amas ouvert',mag:'5,7', saison :'automne'},
{ titre:'NGC891',constellation:'Andromède',image:'images/NGC891-a.jpg', nom:'', type:'galaxie spirale',mag:'9,9', saison :'automne'},
{ titre:'NGC7640',constellation:'Andromède',image:'images/NGC7640-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,3', saison :'automne'},
{ titre:'NGC7686',constellation:'Andromède',image:'images/NGC7686-a.jpg', nom:'', type:'amas ouvert',mag:'5,6', saison :'automne'},
{ titre:'M77',constellation:'Baleine',image:'images/M77-a.jpg', nom:'', type:'galaxie spirale',mag:'8,9', saison :'automne'},
{ titre:'NGC246',constellation:'Baleine',image:'images/NGC246-a.jpg', nom:'Nébuleuse du Crâne', type:'nébuleuse planétaire',mag:'10,4', saison :'automne'},
{ titre:'NGC247',constellation:'Baleine',image:'images/NGC247-a.jpg', nom:'', type:'galaxie spirale',mag:'9,1', saison :'automne'},
{ titre:'NGC691',constellation:'Baleine',image:'images/NGC691-a.jpg', nom:'', type:'galaxie spirale',mag:'11,4', saison :'automne'},
{ titre:'NGC936',constellation:'Baleine',image:'images/NGC936-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'7,9', saison :'automne'},
{ titre:'NGC1055',constellation:'Baleine',image:'images/NGC1055-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,6', saison :'automne'},
{ titre:'NGC1087',constellation:'Baleine',image:'images/NGC1087-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'10,9', saison :'automne'},
{ titre:'NGC1052',constellation:'Baleine',image:'images/NGC1052-a.jpg', nom:'', type:'galaxie elliptique',mag:'10,5', saison :'automne'},
{ titre:'NGC1073',constellation:'Baleine',image:'images/NGC1073-a.jpg', nom:'', type:'spirale barrée',mag:'10,8', saison :'automne'},
{ titre:'NGC1042',constellation:'Baleine',image:'images/NGC1042-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'11', saison :'automne'},
{ titre:'NGC864',constellation:'Baleine',image:'images/NGC864-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'11', saison :'automne'},
{ titre:'NGC1090',constellation:'Baleine',image:'images/NGC1090-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,9', saison :'automne'},
{ titre:'NGC1015',constellation:'Baleine',image:'images/NGC1015-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'12,3', saison :'automne'},
{ titre:'NGC772',constellation:'Bélier',image:'images/NGC772-a.jpg', nom:'', type:'galaxie spirale',mag:'10,3', saison :'automne'},
{ titre:'NGC691',constellation:'Bélier',image:'images/NGC691-a.jpg', nom:'', type:'galaxie spirale',mag:'11,5', saison :'automne'},
{ titre:'NGC1084',constellation:'Eridan',image:'images/NGC1084-a.jpg', nom:'', type:'galaxie spirale',mag:'10,7', saison :'automne'},
{ titre:'M15',constellation:'Pégase',image:'images/M15-a.jpg', nom:'Nuage de Pégase', type:'amas globulaire',mag:'6,2', saison :'automne'},
{ titre:'NGC7331',constellation:'Pégase',image:'images/NGC7331-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'9,5', saison :'automne'},
{ titre:'NGC7814',constellation:'Pégase',image:'images/NGC7814-a.jpg', nom:'', type:'galaxie spirale',mag:'10,6', saison :'automne'},
{ titre:'NGC7626',constellation:'Pégase',image:'images/NGC7626-a.jpg', nom:'', type:'galaxie elliptique',mag:'11,1', saison :'automne'},
{ titre:'NGC7619',constellation:'Pégase',image:'images/NGC7619-a.jpg', nom:'', type:'galaxie elliptique',mag:'11,1', saison :'automne'},
{ titre:'NGC7457',constellation:'Pégase',image:'images/NGC7457-a.jpg', nom:'', type:'galaxie elliptique',mag:'11,2', saison :'automne'},
{ titre:'NGC7448',constellation:'Pégase',image:'images/NGC7448-a.jpg', nom:'', type:'galaxie spirale',mag:'11,7', saison :'automne'},
{ titre:'NGC7217',constellation:'Pégase',image:'images/NGC7217-a.jpg', nom:'', type:'galaxie spirale à anneau',mag:'11', saison :'automne'},
{ titre:'NGC7479',constellation:'Pégase',image:'images/NGC7479-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11', saison :'automne'},
{ titre:'NGC7332',constellation:'Pégase',image:'images/NGC7332-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'12', saison :'automne'},
{ titre:'NGC7339',constellation:'Pégase',image:'images/NGC7339-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'12,2', saison :'automne'},
{ titre:'NGC7318',constellation:'Pégase',image:'images/NGC7318-a.jpg', nom:'Quintet de Stephan', type:'galaxie',mag:'14', saison :'automne'},
{ titre:'NGC7335',constellation:'Pégase',image:'images/NGC7335-a.jpg', nom:'', type:'galaxie',mag:'13,3', saison :'automne'},
{ titre:'NGC7337',constellation:'Pégase',image:'images/NGC7337-a.jpg', nom:'', type:'galaxie',mag:'11,4', saison :'automne'},
{ titre:'NGC7741',constellation:'Pégase',image:'images/NGC7741-a.jpg', nom:'', type:'galaxie spirale',mag:'11,8', saison :'automne'},
{ titre:'NGC7742',constellation:'Pégase',image:'images/NGC7742-a.jpg', nom:'', type:'galaxie spirale',mag:'12,3', saison :'automne'},
{ titre:'M34',constellation:'Persée',image:'images/M34-a.jpg', nom:'', type:'amas ouvert',mag:'5,5', saison :'automne'},
{ titre:'M76',constellation:'Persée',image:'images/M76-a.jpg', nom:'Little Dumbell (Petite Haltère)', type:'nébuleuse planétaire',mag:'10,1', saison :'automne'},
{ titre:'NGC869',constellation:'Persée',image:'images/NGC869-a.jpg', nom:'Double amas de Persée', type:'amas ouverts',mag:'5,3', saison :'automne'},
{ titre:'NGC884',constellation:'Persée',image:'images/NGC884-a.jpg', nom:'Double amas de Persée', type:'amas ouverts',mag:'6,1', saison :'automne'},
{ titre:'NGC1003',constellation:'Persée',image:'images/NGC1003-a.jpg', nom:'', type:'galaxie spirale',mag:'11,5', saison :'automne'},
{ titre:'NGC1342',constellation:'Persée',image:'images/NGC1342-a.jpg', nom:'', type:'amas ouvert',mag:'6,7', saison :'automne'},
{ titre:'NGC1582',constellation:'Persée',image:'images/NGC1582-a.jpg', nom:'', type:'amas ouvert',mag:'7', saison :'automne'},
{ titre:'NGC1023',constellation:'Persée',image:'images/NGC1023-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'9,4', saison :'automne'},
{ titre:'NGC1499',constellation:'Persée',image:'images/NGC1499-a.jpg', nom:'Nébuleuse California (Hbeta)', type:'Nébuleuse',mag:'4,1', saison :'automne'},
{ titre:'M74',constellation:'Poissons',image:'images/M74-a.jpg', nom:'', type:'galaxie spirale',mag:'9,4', saison :'automne'},
{ titre:'NGC660',constellation:'Poissons',image:'images/NGC660-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,2', saison :'automne'},
{ titre:'NGC7314',constellation:'Poisson Austral',image:'images/NGC7314-a.jpg', nom:'', type:'galaxie spirale',mag:'11', saison :'automne'},
{ titre:'M2',constellation:'Verseau',image:'images/M2-a.jpg', nom:'', type:'amas globulaire',mag:'6,5', saison :'automne'},
{ titre:'M72',constellation:'Verseau',image:'images/M72-a.jpg', nom:'', type:'amas globulaire',mag:'9,3', saison :'automne'},
{ titre:'M73',constellation:'Verseau',image:'images/M73-a.jpg', nom:'', type:'amas globulaire',mag:'9', saison :'automne'},
{ titre:'NGC7009',constellation:'Verseau',image:'images/NGC7009-a.jpg', nom:'Nébuleuse Saturne', type:'nébuleuse planétaire',mag:'8,3', saison :'automne'},
{ titre:'NGC7293',constellation:'Verseau',image:'images/NGC7293-a.jpg', nom:'Nébuleuse Hélix', type:'nébuleuse planétaire',mag:'6,3', saison :'automne'},
{ titre:'NGC7606',constellation:'Verseau',image:'images/NGC7606-a.jpg', nom:'', type:'galaxie spirale',mag:'10,8', saison :'automne'},
{ titre:'NGC7184',constellation:'Verseau',image:'images/NGC7184-a.jpg', nom:'', type:'galaxie spirale',mag:'10,9', saison :'automne'},
{ titre:'NGC7727',constellation:'Verseau',image:'images/NGC7727-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,8', saison :'automne'},
{ titre:'NGC7723',constellation:'Verseau',image:'images/NGC7723-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,2', saison :'automne'},
{ titre:'NGC7721',constellation:'Verseau',image:'images/NGC7721-a.jpg', nom:'', type:'galaxie spirale',mag:'11,6', saison :'automne'},
{ titre:'NGC253',constellation:'Sculpteur',image:'images/NGC253-a.jpg', nom:'', type:'galaxie spirale',mag:'7,2', saison :'automne'},
{ titre:'NGC288',constellation:'Sculpteur',image:'images/NGC288-a.jpg', nom:'', type:'amas globulaire',mag:'8,1', saison :'automne'},
{ titre:'NGC289',constellation:'Sculpteur',image:'images/NGC289-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,9', saison :'automne'},
{ titre:'M33',constellation:'Triangle',image:'images/M33-a.jpg', nom:'Galaxie du Triangle', type:'galaxie spirale',mag:'5,7', saison :'automne'},
{ titre:'NGC672',constellation:'Triangle',image:'images/NGC672-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,9', saison :'automne'},
{ titre:'IC1727',constellation:'Triangle',image:'images/IC1727-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,2', saison :'automne'},
{ titre:'NGC925',constellation:'Triangle',image:'images/NGC925-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,1', saison :'automne'},
{ titre:'NGC784',constellation:'Triangle',image:'images/NGC784-a.jpg', nom:'', type:'galaxie spirale barrée naine',mag:'12,2', saison :'automne'},
{ titre:'M44',constellation:'Cancer',image:'images/M44-a.jpg', nom:'Amas de la Ruche (de la crèche)', type:'amas ouvert',mag:'3,7', saison :'hiver'},
{ titre:'M67',constellation:'Cancer',image:'images/M67-a.jpg', nom:'', type:'amas ouvert',mag:'6,1', saison :'hiver'},
{ titre:'NGC2775',constellation:'Cancer',image:'images/NGC2775-a.jpg', nom:'', type:'galaxie spirale',mag:'11', saison :'hiver'},
{ titre:'M36',constellation:'Cocher',image:'images/M36-a.jpg', nom:'', type:'amas ouvert',mag:'6,3', saison :'hiver'},
{ titre:'M37',constellation:'Cocher',image:'images/M37-a.jpg', nom:'', type:'amas ouvert',mag:'6,2', saison :'hiver'},
{ titre:'M38',constellation:'Cocher',image:'images/M38-a.jpg', nom:'', type:'amas ouvert',mag:'7,4', saison :'hiver'},
{ titre:'NGC1664',constellation:'Cocher',image:'images/NGC1664-a.jpg', nom:'', type:'amas ouvert',mag:'7,6', saison :'hiver'},
{ titre:'NGC1893',constellation:'Cocher',image:'images/NGC1893-a.jpg', nom:'(au cœur de la nébuleuse en émission IC 410)', type:'amas ouvert',mag:'7,5', saison :'hiver'},
{ titre:'NGC1907',constellation:'Cocher',image:'images/NGC1907-a.jpg', nom:'', type:'amas ouvert',mag:'8,2', saison :'hiver'},
{ titre:'NGC1931',constellation:'Cocher',image:'images/NGC1931-a.jpg', nom:'', type:'amas ouvert + nébuleuse en émission',mag:'10,1', saison :'hiver'},
{ titre:'IC410',constellation:'Cocher',image:'images/IC410-a.jpg', nom:'Nébuleuse du Tétard', type:'nébuleuse en émission',mag:'10', saison :'hiver'},
{ titre:'M35',constellation:'Gémeaux',image:'images/M35-a.jpg', nom:'', type:'amas ouvert',mag:'5,3', saison :'hiver'},
{ titre:'NGC2158',constellation:'Gémeaux',image:'images/NGC2158-a.jpg', nom:'', type:'amas ouvert',mag:'8,6', saison :'hiver'},
{ titre:'NGC2392',constellation:'Gémeaux',image:'images/NGC2392-a.jpg', nom:'Nébuleuse de l\'Esquimau (ou du Clown)', type:'nébuleuse planétaire',mag:'8,6', saison :'hiver'},
{ titre:'M41',constellation:'Grand Chien',image:'images/M41-a.jpg', nom:'', type:'amas ouvert',mag:'4,5', saison :'hiver'},
{ titre:'M50',constellation:'Licorne',image:'images/M50-a.jpg', nom:'', type:'amas ouvert',mag:'5,9', saison :'hiver'},
{ titre:'NGC2237',constellation:'Licorne',image:'images/NGC2237-a.jpg', nom:'Nébuleuse de la Rosette', type:'nébuleuse',mag:'5,5', saison :'hiver'},
{ titre:'NGC2244',constellation:'Licorne',image:'images/NGC2244-a.jpg', nom:'dans la nébuleuse de la Rosette', type:'amas ouvert',mag:'5,3', saison :'hiver'},
{ titre:'NGC2264',constellation:'Licorne',image:'images/NGC2264-a.jpg', nom:'Nébuleuse du Cone (sapin de Noel)', type:'nébuleuse',mag:'4,1', saison :'hiver'},
{ titre:'NGC2261',constellation:'Licorne',image:'images/NGC2261-a.jpg', nom:'Nébuleuse variable de Hubble', type:'nébuleuse',mag:'~10', saison :'hiver'},
{ titre:'M79',constellation:'Lièvre',image:'images/M79-a.jpg', nom:'', type:'amas globulaire',mag:'8,6', saison :'hiver'},
{ titre:'NGC1964',constellation:'Lièvre',image:'images/NGC1964-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'10,8', saison :'hiver'},
{ titre:'NGC1832',constellation:'Lièvre',image:'images/NGC1832-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,3', saison :'hiver'},
{ titre:'NGC2863',constellation:'Lynx',image:'images/NGC2863-a.jpg', nom:'', type:'galaxie spirale',mag:'9,8', saison :'hiver'},
{ titre:'NGC2782',constellation:'Lynx',image:'images/NGC2782-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'11,4', saison :'hiver'},
{ titre:'M42',constellation:'Orion',image:'images/M42-a.jpg', nom:'Grande nébuleuse d\'Orion', type:'nébuleuse diffuse',mag:'4', saison :'hiver'},
{ titre:'M43',constellation:'Orion',image:'images/M43-a.jpg', nom:'Nébuleuse de Mairan', type:'nébuleuse diffuse',mag:'9', saison :'hiver'},
{ titre:'M78',constellation:'Orion',image:'images/M78-a.jpg', nom:'(magnitude )', type:'nébuleuse diffuse',mag:'8,3', saison :'hiver'},
{ titre:'NGC2022',constellation:'Orion',image:'images/NGC2022-a.jpg', nom:'Nébuleuse de la Clavicule (filtre O3 ou UHC)', type:'nébuleuse planétaire',mag:'11,7', saison :'hiver'},
{ titre:'NGC2024',constellation:'Orion',image:'images/NGC2024-a.jpg', nom:'Nébuleuse de la Flamme (filtre O3 ou UHC)', type:'nébuleuse en émission',mag:'11,7', saison :'hiver'},
{ titre:'M46',constellation:'Poupe',image:'images/M46-a.jpg', nom:'', type:'amas ouvert',mag:'6,6', saison :'hiver'},
{ titre:'M47',constellation:'Poupe',image:'images/M47-a.jpg', nom:'', type:'amas ouvert',mag:'10,8', saison :'hiver'},
{ titre:'M93',constellation:'Poupe',image:'images/M93-a.jpg', nom:'', type:'amas ouvert',mag:'10,8', saison :'hiver'},
{ titre:'NGC2438',constellation:'Poupe',image:'images/NGC2438-a.jpg', nom:'à l\'intérieur de M46', type:'nébuleuse planétaire',mag:'10,8', saison :'hiver'},
{ titre:'NGC2440',constellation:'Poupe',image:'images/NGC2440-a.jpg', nom:'Nébuleuse de la chauve souris, OIII', type:'nébuleuse planétaire',mag:'9,4', saison :'hiver'},
{ titre:'M1',constellation:'Taureau',image:'images/M1-a.jpg', nom:'', type:'nébuleuse (vestiges de SN)',mag:'8,4', saison :'hiver'},
{ titre:'M45',constellation:'Taureau',image:'images/M45-a.jpg', nom:'Les Pléiades', type:'amas ouvert',mag:'1,6', saison :'hiver'},
{ titre:'NGC1514',constellation:'Taureau',image:'images/NGC1514-a.jpg', nom:'Nébuleuse de la boule de Cristal (ou de la Rosée) avec OIII', type:'nébuleuse planétaire',mag:'10,8', saison :'hiver'},
{ titre:'NGC1807',constellation:'Taureau',image:'images/NGC1807-a.jpg', nom:'', type:'amas ouvert',mag:'7', saison :'hiver'},
{ titre:'NGC1817',constellation:'Taureau',image:'images/NGC1817-a.jpg', nom:'', type:'amas ouvert',mag:'7,7', saison :'hiver'},
{ titre:'NGC5466',constellation:'Bouvier',image:'images/NGC5466-a.jpg', nom:'', type:'amas globulaire',mag:'9,1', saison :'printemps'},
{ titre:'M53',constellation:'Chevelure de Bérénice',image:'images/M53-a.jpg', nom:'', type:'amas globulaire',mag:'7,6', saison :'printemps'},
{ titre:'M64',constellation:'Chevelure de Bérénice',image:'images/M64-a.jpg', nom:'Galaxie de l\'oeil noir', type:'galaxie spirale',mag:'8,5', saison :'printemps'},
{ titre:'M94',constellation:'Chevelure de Bérénice',image:'images/M94-a.jpg', nom:'', type:'galaxie spirale',mag:'8,2', saison :'printemps'},
{ titre:'M100',constellation:'Chevelure de Bérénice',image:'images/M100-a.jpg', nom:'Galaxie du Sèche Cheveux', type:'galaxie spirale',mag:'9,3', saison :'printemps'},
{ titre:'M85',constellation:'Chevelure de Bérénice',image:'images/M85-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'9,1', saison :'printemps'},
{ titre:'M91',constellation:'Chevelure de Bérénice',image:'images/M91-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,2', saison :'printemps'},
{ titre:'NGC4565',constellation:'Chevelure de Bérénice',image:'images/NGC4565-a.jpg', nom:'Galaxie de l\'Aiguille', type:'galaxie spirale',mag:'9,6', saison :'printemps'},
{ titre:'NGC4725',constellation:'Chevelure de Bérénice',image:'images/NGC4725-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'9,4', saison :'printemps'},
{ titre:'NGC4559',constellation:'Chevelure de Bérénice',image:'images/NGC4559-a.jpg', nom:'', type:'galaxie spirale',mag:'10', saison :'printemps'},
{ titre:'NGC4889',constellation:'Chevelure de Bérénice',image:'images/NGC4889-a.jpg', nom:'', type:'galaxie elliptique super géante',mag:'11,4', saison :'printemps'},
{ titre:'NGC4394',constellation:'Chevelure de Bérénice',image:'images/NGC4394-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,9', saison :'printemps'},
{ titre:'NGC4350',constellation:'Chevelure de Bérénice',image:'images/NGC4350-a.jpg', nom:'en duo avec 4340', type:'galaxie lenticulaire',mag:'11', saison :'printemps'},
{ titre:'NGC4340',constellation:'Chevelure de Bérénice',image:'images/NGC4340-a.jpg', nom:'en duo avec 4350', type:'galaxie lenticulaire barrée',mag:'12,1', saison :'printemps'},
{ titre:'M51',constellation:'Chiens de Chasse',image:'images/M51-a.jpg', nom:'Galaxie du Tourbillon', type:'galaxie spirale',mag:'8,4', saison :'printemps'},
{ titre:'M3',constellation:'Chiens de Chasse',image:'images/M3-a.jpg', nom:'', type:'amas globulaire',mag:'6,2', saison :'printemps'},
{ titre:'M63',constellation:'Chiens de Chasse',image:'images/M63-a.jpg', nom:'Galaxie du Tournesol', type:'galaxie spirale',mag:'8,6', saison :'printemps'},
{ titre:'M106',constellation:'Chiens de Chasse',image:'images/M106-a.jpg', nom:'', type:'galaxie spirale',mag:'8,4', saison :'printemps'},
{ titre:'NGC4631',constellation:'Chiens de Chasse',image:'images/NGC4631-a.jpg', nom:'Galaxie de la Baleine', type:'galaxie spirale',mag:'9,2', saison :'printemps'},
{ titre:'NGC4656',constellation:'Chiens de Chasse',image:'images/NGC4656-a.jpg', nom:'Galaxie de la crosse de hockey', type:'galaxie spirale barrée',mag:'10,6', saison :'printemps'},
{ titre:'NGC5033',constellation:'Chiens de Chasse',image:'images/NGC5033-a.jpg', nom:'duo avec 5005', type:'galaxie spirale',mag:'10,2', saison :'printemps'},
{ titre:'NGC5005',constellation:'Chiens de Chasse',image:'images/NGC5005-a.jpg', nom:'duo avec 5033', type:'galaxie spirale intermédiaire',mag:'10,6', saison :'printemps'},
{ titre:'NGC4490',constellation:'Chiens de Chasse',image:'images/NGC4490-a.jpg', nom:'Galaxie du Cocon - avec 4485', type:'galaxie spirale barrée',mag:'9,8', saison :'printemps'},
{ titre:'NGC4244',constellation:'Chiens de Chasse',image:'images/NGC4244-a.jpg', nom:'', type:'galaxie spirale',mag:'7,7', saison :'printemps'},
{ titre:'NGC4111',constellation:'Chiens de Chasse',image:'images/NGC4111-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'10,7', saison :'printemps'},
{ titre:'NGC4449',constellation:'Chiens de Chasse',image:'images/NGC4449-a.jpg', nom:'', type:'galaxie irréeguliere',mag:'10', saison :'printemps'},
{ titre:'NGC4214',constellation:'Chiens de Chasse',image:'images/NGC4214-a.jpg', nom:'', type:'galaxie lenticulaire barrée naine',mag:'10,2', saison :'printemps'},
{ titre:'NGC4618',constellation:'Chiens de Chasse',image:'images/NGC4618-a.jpg', nom:'', type:'galaxie naine barrée naine',mag:'11,2', saison :'printemps'},
{ titre:'NGC4627',constellation:'Chiens de Chasse',image:'images/NGC4627-a.jpg', nom:'Galaxie du Baleineau', type:'galaxie',mag:'12,4', saison :'printemps'},
{ titre:'NGC4361',constellation:'Corbeau',image:'images/NGC4361-a.jpg', nom:'L’arroseur de jardin', type:'nébuleuse Planétaire',mag:'10,9', saison :'printemps'},
{ titre:'NGC4027',constellation:'Corbeau',image:'images/NGC4027-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,7', saison :'printemps'},
{ titre:'NGC4038',constellation:'Corbeau',image:'images/NGC4038-a.jpg', nom:'Les Antennes', type:'galaxies en interaction',mag:'10,3', saison :'printemps'},
{ titre:'NGC4039',constellation:'Corbeau',image:'images/NGC4039-a.jpg', nom:'Les Antennes', type:'galaxies en interaction',mag:'10,6', saison :'printemps'},
{ titre:'M48',constellation:'Hydre',image:'images/M48-a.jpg', nom:'', type:'amas ouvert',mag:'5,5', saison :'printemps'},
{ titre:'M68',constellation:'Hydre',image:'images/M68-a.jpg', nom:'', type:'amas globulaire',mag:'9,7', saison :'printemps'},
{ titre:'NGC3242',constellation:'Hydre',image:'images/NGC3242-a.jpg', nom:'Fantôme de Jupiter', type:'nébuleuse planétaire',mag:'8,6', saison :'printemps'},
{ titre:'M83',constellation:'Hydre',image:'images/M83-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'7,6', saison :'printemps'},
{ titre:'M65',constellation:'Lion',image:'images/M65-a.jpg', nom:'(membre du Triplet du Lion)', type:'galaxie spirale',mag:'9,3', saison :'printemps'},
{ titre:'M66',constellation:'Lion',image:'images/M66-a.jpg', nom:'(membre du Triplet du Lion)', type:'galaxie spirale',mag:'8,9', saison :'printemps'},
{ titre:'NGC3628',constellation:'Lion',image:'images/NGC3628-a.jpg', nom:'Galaxie du Hamburger (membre du Triplet du Lion)', type:'galaxie spirale',mag:'', saison :'printemps'},
{ titre:'M96',constellation:'Lion',image:'images/M96-a.jpg', nom:'(membre du groupe Leo I)', type:'galaxie spirale',mag:'9,2', saison :'printemps'},
{ titre:'M95',constellation:'Lion',image:'images/M95-a.jpg', nom:'(membre du groupe Leo I)', type:'galaxie spirale barrée',mag:'9,7', saison :'printemps'},
{ titre:'M105',constellation:'Lion',image:'images/M105-a.jpg', nom:'(membre du groupe Leo I)', type:'galaxie elliptique',mag:'9,3', saison :'printemps'},
{ titre:'NGC2903',constellation:'Lion',image:'images/NGC2903-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'9', saison :'printemps'},
{ titre:'NGC3384',constellation:'Lion',image:'images/NGC3384-a.jpg', nom:'', type:'galaxie elliptique',mag:'9,9', saison :'printemps'},
{ titre:'NGC3190',constellation:'Lion',image:'images/NGC3190-a.jpg', nom:'', type:'galaxie spirale',mag:'11,1', saison :'printemps'},
{ titre:'NGC3193',constellation:'Lion',image:'images/NGC3193-a.jpg', nom:'', type:'galaxie elliptique',mag:'10,9', saison :'printemps'},
{ titre:'NGC3607',constellation:'Lion',image:'images/NGC3607-a.jpg', nom:'', type:'galaxie lenticulaire',mag:'10,8', saison :'printemps'},
{ titre:'NGC3608',constellation:'Lion',image:'images/NGC3608-a.jpg', nom:'', type:'galaxie elliptique',mag:'10,5', saison :'printemps'},
{ titre:'NGC3521',constellation:'Lion',image:'images/NGC3521-a.jpg', nom:'', type:'galaxie spirale intermédiaire',mag:'9', saison :'printemps'},
{ titre:'NGC3227',constellation:'Lion',image:'images/NGC3227-a.jpg', nom:'', type:'galaxie elliptique - en interaction avec 3226 (Arp 94)',mag:'10,3', saison :'printemps'},
{ titre:'NGC3226',constellation:'Lion',image:'images/NGC3226-a.jpg', nom:'', type:'galaxie naine elliptique - en interaction avec 3227 (Arp 94)',mag:'11,4', saison :'printemps'},
{ titre:'NGC3373',constellation:'Lion',image:'images/NGC3373-a.jpg', nom:'', type:'galaxie spirale',mag:'11,9', saison :'printemps'},
{ titre:'NGC3187',constellation:'Lion',image:'images/NGC3187-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'13,1', saison :'printemps'},
{ titre:'NGC3686',constellation:'Lion',image:'images/NGC3686-a.jpg', nom:'', type:'galaxies',mag:'11,2-11,8', saison :'printemps'},
{ titre:'NGC3684',constellation:'Lion',image:'images/NGC3684-a.jpg', nom:'', type:'galaxies',mag:'11,2-11,8', saison :'printemps'},
{ titre:'NGC3681',constellation:'Lion',image:'images/NGC3681-a.jpg', nom:'', type:'galaxies',mag:'11,2-11,8', saison :'printemps'},
{ titre:'NGC3432',constellation:'Petit Lion',image:'images/NGC3432-a.jpg', nom:'', type:'galaxie spirale',mag:'11,3', saison :'printemps'},
{ titre:'NGC2859',constellation:'Petit Lion',image:'images/NGC2859-a.jpg', nom:'', type:'galaxie lenticulaire barrée',mag:'11,8', saison :'printemps'},
{ titre:'NGC3003',constellation:'Petit Lion',image:'images/NGC3003-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'11,9', saison :'printemps'},
{ titre:'NGC3115',constellation:'Sextant',image:'images/NGC3115-a.jpg', nom:'Galaxie du fuseau', type:'galaxie lenticulaire',mag:'9,9', saison :'printemps'},
{ titre:'NGC3169',constellation:'Sextant',image:'images/NGC3169-a.jpg', nom:'', type:'galaxie spirale',mag:'11,5', saison :'printemps'},
{ titre:'NGC3166',constellation:'Sextant',image:'images/NGC3166-a.jpg', nom:'', type:'galaxie spirale',mag:'11,3', saison :'printemps'},
{ titre:'M104',constellation:'Vierge',image:'images/M104-a.jpg', nom:'Galaxie du Sombrero', type:'galaxie spirale',mag:'8', saison :'printemps'},
{ titre:'M49',constellation:'Vierge',image:'images/M49-a.jpg', nom:'', type:'galaxie elliptique',mag:'8,4', saison :'printemps'},
{ titre:'M58',constellation:'Vierge',image:'images/M58-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'9,7', saison :'printemps'},
{ titre:'M59',constellation:'Vierge',image:'images/M59-a.jpg', nom:'', type:'galaxie elliptique',mag:'9,6', saison :'printemps'},
{ titre:'M60',constellation:'Vierge',image:'images/M60-a.jpg', nom:'', type:'galaxie elliptique',mag:'8,8', saison :'printemps'},
{ titre:'M61',constellation:'Vierge',image:'images/M61-a.jpg', nom:'', type:'galaxie spirale',mag:'9,7', saison :'printemps'},
{ titre:'M84',constellation:'Vierge',image:'images/M84-a.jpg', nom:'(membre de la chaine de Markarian)', type:'galaxie lenticulaire',mag:'9,1', saison :'printemps'},
{ titre:'M86',constellation:'Vierge',image:'images/M86-a.jpg', nom:'(membre de la chaine de Markarian)', type:'galaxie lenticulaire',mag:'8,9', saison :'printemps'},
{ titre:'M87',constellation:'Vierge',image:'images/M87-a.jpg', nom:'(membre de la chaine de Markarian)', type:'galaxie elliptique',mag:'8,6', saison :'printemps'},
{ titre:'NGC4697',constellation:'Vierge',image:'images/NGC4697-a.jpg', nom:'', type:'galaxie elliptique',mag:'9,3', saison :'printemps'},
{ titre:'NGC5634',constellation:'Vierge',image:'images/NGC5634-a.jpg', nom:'', type:'amas globulaire',mag:'9,5', saison :'printemps'},
{ titre:'NGC5746',constellation:'Vierge',image:'images/NGC5746-a.jpg', nom:'', type:'galaxie spirale barrée',mag:'10,6', saison :'printemps'},
{ titre:'NGC4385',constellation:'Vierge',image:'images/NGC4385-a.jpg', nom:'', type:'galaxie',mag:'12,5', saison :'printemps'},
{ titre:'NGC4435',constellation:'Vierge',image:'images/NGC4435-a.jpg', nom:'Galaxies des Yeux (membres de la chaine de Markarian)', type:'galaxies lenticulaire barree',mag:'10,8', saison :'printemps'},
{ titre:'NGC4438',constellation:'Vierge',image:'images/NGC4438-a.jpg', nom:'Galaxies des Yeux (membres de la chaine de Markarian)', type:'galaxie',mag:'10,2', saison :'printemps'},
{ titre:'NGC6781',constellation:'Aigle',image:'images/NGC6781-a.jpg', nom:'', type:'nébuleuse planétaire',mag:'11,8', saison :'été'},
{ titre:'M30',constellation:'Capricorne',image:'images/M30-a.jpg', nom:'', type:'amas globulaire',mag:'7,2', saison :'été'},
{ titre:'M29',constellation:'Cygne',image:'images/M29-a.jpg', nom:'', type:'amas ouvert',mag:'7,1', saison :'été'},
{ titre:'M39',constellation:'Cygne',image:'images/M39-a.jpg', nom:'', type:'amas ouvert',mag:'4,6', saison :'été'},
{ titre:'NGC6888',constellation:'Cygne',image:'images/NGC6888-a.jpg', nom:'Nébuleuse du Croissant', type:'nébuleuse en émission',mag:'10', saison :'été'},
{ titre:'NGC6826',constellation:'Cygne',image:'images/NGC6826-a.jpg', nom:'Nébuleuse Clignotante', type:'nébuleuse planétaire',mag:'8,8', saison :'été'},
{ titre:'NGC6960',constellation:'Cygne',image:'images/NGC6960-a.jpg', nom:'Les Dentelles du Cygne', type:'Résidus de SN',mag:'7', saison :'été'},
{ titre:'NGC6992',constellation:'Cygne',image:'images/NGC6992-a.jpg', nom:'Les Dentelles du Cygne', type:'Résidus de SN',mag:'7', saison :'été'},
{ titre:'NGC6995',constellation:'Cygne',image:'images/NGC6995-a.jpg', nom:'Les Dentelles du Cygne', type:'Résidus de SN',mag:'7', saison :'été'},
{ titre:'NGC7027',constellation:'Cygne',image:'images/NGC7027-a.jpg', nom:'Nébuleuse du Rectangle vert', type:'nébuleuse planétaire',mag:'8,5', saison :'été'},
{ titre:'NGC7000',constellation:'Cygne',image:'images/NGC7000-a.jpg', nom:'Nébuleuse North America (filtre OIII,UHE)', type:'nébuleuse en émission',mag:'6', saison :'été'},
{ titre:'NGC6934',constellation:'Dauphin',image:'images/NGC6934-a.jpg', nom:'', type:'amas globulaire',mag:'8,9', saison :'été'},
{ titre:'NGC6905',constellation:'Dauphin',image:'images/NGC6905-a.jpg', nom:'', type:'nébuleuse planétaire',mag:'10,9', saison :'été'},
{ titre:'M11',constellation:'Ecu de Sobieski',image:'images/M11-a.jpg', nom:'Amas du Canard Sauvage', type:'amas ouvert',mag:'6,3', saison :'été'},
{ titre:'M26',constellation:'Ecu de Sobieski',image:'images/M26-a.jpg', nom:'', type:'amas ouvert',mag:'8', saison :'été'},
{ titre:'NGC6712',constellation:'Ecu de Sobieski',image:'images/NGC6712-a.jpg', nom:'', type:'amas globulaire',mag:'8,1', saison :'été'},
{ titre:'M71',constellation:'Flèche',image:'images/M71-a.jpg', nom:'', type:'amas globulaire',mag:'8,2', saison :'été'},
{ titre:'M13',constellation:'Hercule',image:'images/M13-a.jpg', nom:'Grand amas d\'Hercule', type:'amas globulaire',mag:'5,8', saison :'été'},
{ titre:'M92',constellation:'Hercule',image:'images/M92-a.jpg', nom:'', type:'amas globulaire',mag:'6,4', saison :'été'},
{ titre:'NGC6229',constellation:'Hercule',image:'images/NGC6229-a.jpg', nom:'', type:'amas globulaire',mag:'9,4', saison :'été'},
{ titre:'NGC6207',constellation:'Hercule',image:'images/NGC6207-a.jpg', nom:'', type:'galaxie spirale',mag:'10,1', saison :'été'},
{ titre:'NGC6210',constellation:'Hercule',image:'images/NGC6210-a.jpg', nom:'Nébuleuse de la Tortue', type:'nébuleuse planétaire',mag:'9,7', saison :'été'},
{ titre:'M57',constellation:'Lyre',image:'images/M57-a.jpg', nom:'Nébuleuse de l\'Anneau', type:'nébuleuse planétaire',mag:'8,8', saison :'été'},
{ titre:'M56',constellation:'Lyre',image:'images/M56-a.jpg', nom:'', type:'amas globulaire',mag:'8,3', saison :'été'},
{ titre:'M9',constellation:'Ophiuchus',image:'images/M9-a.jpg', nom:'', type:'amas globulaire',mag:'7,7', saison :'été'},
{ titre:'M10',constellation:'Ophiuchus',image:'images/M10-a.jpg', nom:'', type:'amas globulaire',mag:'6,6', saison :'été'},
{ titre:'M12',constellation:'Ophiuchus',image:'images/M12-a.jpg', nom:'', type:'amas globulaire',mag:'6,7', saison :'été'},
{ titre:'M14',constellation:'Ophiuchus',image:'images/M14-a.jpg', nom:'', type:'amas globulaire',mag:'7,6', saison :'été'},
{ titre:'M19',constellation:'Ophiuchus',image:'images/M19-a.jpg', nom:'', type:'amas globulaire',mag:'6,8', saison :'été'},
{ titre:'M62',constellation:'Ophiuchus',image:'images/M62-a.jpg', nom:'', type:'amas globulaire',mag:'6,5', saison :'été'},
{ titre:'M107',constellation:'Ophiuchus',image:'images/M107-a.jpg', nom:'', type:'amas globulaire',mag:'8,9', saison :'été'},
{ titre:'NGC6633',constellation:'Ophiuchus',image:'images/NGC6633-a.jpg', nom:'', type:'amas ouvert',mag:'4,6', saison :'été'},
{ titre:'NGC6572',constellation:'Ophiuchus',image:'images/NGC6572-a.jpg', nom:'Nébuleuse de l\'Emeraude', type:'nébuleuse planétaire',mag:'11,3', saison :'été'},
{ titre:'NGC6369',constellation:'Ophiuchus',image:'images/NGC6369-a.jpg', nom:'Le petit Fantome', type:'nébuleuse planétaire',mag:'12,9', saison :'été'},
{ titre:'M27',constellation:'Petit Renard',image:'images/M27-a.jpg', nom:'Nébuleuse de l\'Haltère (Dumbell)', type:'nébuleuse planétaire',mag:'7,4', saison :'été'},
{ titre:'M8',constellation:'Sagittaire',image:'images/M8-a.jpg', nom:'Nébuleuse de la Lagune', type:'nébuleuse en émission',mag:'6', saison :'été'},
{ titre:'M17',constellation:'Sagittaire',image:'images/M17-a.jpg', nom:'Nébuleuse Oméga', type:'nébuleuse en émission',mag:'6', saison :'été'},
{ titre:'M20',constellation:'Sagittaire',image:'images/M20-a.jpg', nom:'Nébuleuse Trifide', type:'nébuleuse diffuse',mag:'9', saison :'été'},
{ titre:'M18',constellation:'Sagittaire',image:'images/M18-a.jpg', nom:'', type:'amas ouvert',mag:'7,5', saison :'été'},
{ titre:'M21',constellation:'Sagittaire',image:'images/M21-a.jpg', nom:'', type:'amas ouvert',mag:'6,5', saison :'été'},
{ titre:'M22',constellation:'Sagittaire',image:'images/M22-a.jpg', nom:'Amas duSagittaire', type:'amas globulaire',mag:'5,1', saison :'été'},
{ titre:'M28',constellation:'Sagittaire',image:'images/M28-a.jpg', nom:'', type:'amas globulaire',mag:'6,8', saison :'été'},
{ titre:'M54',constellation:'Sagittaire',image:'images/M54-a.jpg', nom:'', type:'amas globulaire',mag:'7,6', saison :'été'},
{ titre:'M55',constellation:'Sagittaire',image:'images/M55-a.jpg', nom:'', type:'amas globulaire',mag:'6,3', saison :'été'},
{ titre:'M69',constellation:'Sagittaire',image:'images/M69-a.jpg', nom:'', type:'amas globulaire',mag:'8,3', saison :'été'},
{ titre:'M70',constellation:'Sagittaire',image:'images/M70-a.jpg', nom:'', type:'amas globulaire',mag:'7,8', saison :'été'},
{ titre:'NGC6569',constellation:'Sagittaire',image:'images/NGC6569-a.jpg', nom:'', type:'amas globulaire',mag:'8,4', saison :'été'},
{ titre:'NGC6522',constellation:'Sagittaire',image:'images/NGC6522-a.jpg', nom:'', type:'amas globulaire',mag:'10,5', saison :'été'},
{ titre:'NGC6528',constellation:'Sagittaire',image:'images/NGC6528-a.jpg', nom:'', type:'amas globulaire',mag:'11', saison :'été'},
{ titre:'M80',constellation:'Scorpion',image:'images/M80-a.jpg', nom:'', type:'amas globulaire',mag:'7,3', saison :'été'},
{ titre:'M4',constellation:'Scorpion',image:'images/M4-a.jpg', nom:'', type:'amas globulaire',mag:'5,6', saison :'été'},
{ titre:'M6',constellation:'Scorpion',image:'images/M6-a.jpg', nom:'Amas du Papillon', type:'amas ouvert',mag:'4,2', saison :'été'},
{ titre:'M7',constellation:'Scorpion',image:'images/M7-a.jpg', nom:'Amas de Ptolémée', type:'amas ouvert',mag:'3,3', saison :'été'},
{ titre:'NGC6302',constellation:'Scorpion',image:'images/NGC6302-a.jpg', nom:'nébuleuse du Papillon', type:'nébuleuse planétaire bipolaire',mag:'9,6', saison :'été'},
{ titre:'M5',constellation:'Serpent',image:'images/M5-a.jpg', nom:'', type:'amas globulaire',mag:'5,6', saison :'été'},
{ titre:'M16',constellation:'Serpent',image:'images/M16-a.jpg', nom:'(associé à la nébuleuse de l\'Aigle)', type:'amas ouvert',mag:'6', saison :'été'},
];
