const objetsMessier = [
  { image: 'images/M1-a.jpg', nom: 'Nébuleuse du Crabe', constellation: 'Taureau' },
  { image: 'images/M2-a.jpg', nom: 'Amas globulaire', constellation: 'Hercule' },
  { image: 'images/M3-a.jpg', nom: 'Amas globulaire', constellation: 'Vierge' },
  { image: 'images/M4-a.jpg', nom: 'Amas globulaire', constellation: 'Scorpion' },
  { image: 'images/M5-a.jpg', nom: 'Amas globulaire', constellation: 'Serpent' },
  { image: 'images/M6-a.jpg', nom: 'Amas du papillon', constellation: 'Scorpion' },
  { image: 'images/M7-a.jpg', nom: 'Amas ouvert', constellation: 'Scorpion' },
  { image: 'images/M8-a.jpg', nom: 'Nébuleuse de la Lagune', constellation: 'Sagittaire' },
  { image: 'images/M9-a.jpg', nom: 'Amas globulaire', constellation: 'Serpent' },
  { image: 'images/M10-a.jpg', nom: 'Amas globulaire', constellation: 'Hercule' },
  { image: 'images/M11-a.jpg', nom: 'Amas du Canard sauvage', constellation: 'Écu de Sobieski' },
  { image: 'images/M12-a.jpg', nom: 'Amas globulaire', constellation: 'Ophiuchus' },
  { image: 'images/M13-a.jpg', nom: 'Amas d\'Hercule', constellation: 'Hercule' },
  { image: 'images/M14-a.jpg', nom: 'Amas globulaire', constellation: 'Ophiuchus' },
  { image: 'images/M15-a.jpg', nom: 'Amas globulaire', constellation: 'Pégase' },
  { image: 'images/M16-a.jpg', nom: 'Nébuleuse de l\'Aigle', constellation: 'Serpent' },
  { image: 'images/M17-a.jpg', nom: 'Nébuleuse Oméga', constellation: 'Sagittaire' },
  { image: 'images/M18-a.jpg', nom: 'Amas ouvert', constellation: 'Sagittaire' },
  { image: 'images/M19-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M20-a.jpg', nom: 'Nébuleuse Trifide', constellation: 'Sagittaire' },
  { image: 'images/M21-a.jpg', nom: 'Amas ouvert', constellation: 'Sagittaire' },
  { image: 'images/M22-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M23-a.jpg', nom: 'Amas ouvert', constellation: 'Sagittaire' },
  { image: 'images/M24-a.jpg', nom: 'Petit nuage du Sagittaire', constellation: 'Sagittaire' },
  { image: 'images/M25-a.jpg', nom: 'Amas ouvert', constellation: 'Sagittaire' },
  { image: 'images/M26-a.jpg', nom: 'Amas ouvert', constellation: 'Sagittaire' },
  { image: 'images/M27-a.jpg', nom: 'Nébuleuse de l\'Haltère (Dumbbell) ', constellation: 'Petit Renard' },
  { image: 'images/M28-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M29-a.jpg', nom: 'Amas ouvert', constellation: 'Cocher' },
  { image: 'images/M30-a.jpg', nom: 'Amas globulaire', constellation: 'Capricorne ' },
  { image: 'images/M31-a.jpg', nom: 'Galaxie d\'Andromède', constellation: 'Andromède ' },
  { image: 'images/M32-a.jpg', nom: 'Galaxie elliptique', constellation: 'Andromède ' },
  { image: 'images/M33-a.jpg', nom: 'Galaxie du Triangle', constellation: 'Triangle' },
  { image: 'images/M34-a.jpg', nom: 'Amas ouvert', constellation: 'Persée' },
  { image: 'images/M35-a.jpg', nom: 'Amas ouvert', constellation: 'Gémeaux' },
  { image: 'images/M36-a.jpg', nom: 'Amas ouvert', constellation: 'Gémeaux' },
  { image: 'images/M37-a.jpg', nom: 'Amas ouvert', constellation: 'Gémeaux' },
  { image: 'images/M38-a.jpg', nom: 'Amas ouvert ', constellation: 'Cocher' },
  { image: 'images/M39-a.jpg', nom: 'Amas ouvert', constellation: 'Cygne' },
  { image: 'images/M40-a.jpg', nom: 'Étoile double (Winnecke 4)', constellation: 'Grande Ourse' },
  { image: 'images/M41-a.jpg', nom: 'Amas ouvert', constellation: 'Grand Chien' },
  { image: 'images/M42-a.jpg', nom: 'Grande Nébuleuse d\'Orion', constellation: 'Orion' },
  { image: 'images/M43-a.jpg', nom: 'Nébuleuse de la Tête de Cheval', constellation: 'Orion' },
  { image: 'images/M44-a.jpg', nom: 'Amas ouvert ', constellation: 'Cancer' },
  { image: 'images/M45-a.jpg', nom: 'Pléiades ', constellation: 'Taureau' },
  { image: 'images/M46-a.jpg', nom: 'Amas ouvert', constellation: 'Petit Chien' },
  { image: 'images/M47-a.jpg', nom: 'Amas ouvert', constellation: 'Poupe' },
  { image: 'images/M48-a.jpg', nom: 'Amas ouvert', constellation: 'Poupe' },
  { image: 'images/M49-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge' },
  { image: 'images/M50-a.jpg', nom: 'Amas ouvert de la Licorne ', constellation: 'Licorne' },
  { image: 'images/M51-a.jpg', nom: 'Galaxie du Tourbillon ', constellation: 'Chiens de chasse' },
  { image: 'images/M52-a.jpg', nom: 'Amas ouvert', constellation: 'Cassiopée' },
  { image: 'images/M53-a.jpg', nom: 'Amas globulaire', constellation: 'Chevelure de Bérénice' },
  { image: 'images/M54-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M55-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M56-a.jpg', nom: 'Amas globulaire', constellation: 'Lyre' },
  { image: 'images/M57-b.jpg', nom: 'Nébuleuse de l\'Anneau', constellation: 'Lyre' },
  { image: 'images/M58-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Vierge' },
  { image: 'images/M59-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge' },
  { image: 'images/M60-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge' },
  { image: 'images/M61-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Vierge' },
  { image: 'images/M62-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M63-a.jpg', nom: 'Galaxie tournesol', constellation: 'Chiens de chasse' },
  { image: 'images/M64-a.jpg', nom: 'Galaxie spirale', constellation: 'Chiens de chasse' },
  { image: 'images/M65-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion' },
  { image: 'images/M66-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion' },
  { image: 'images/M67-a.jpg', nom: 'Amas ouvert', constellation: 'Cancer' },
  { image: 'images/M68-a.jpg', nom: 'Amas globulaire', constellation: 'Lion' },
  { image: 'images/M69-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M70-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M71-a.jpg', nom: 'Amas globulaire', constellation: 'Flèche' },
  { image: 'images/M72-a.jpg', nom: 'Amas globulaire', constellation: 'Verseau' },
  { image: 'images/M73-a.jpg', nom: 'Quatuor d\'étoiles ', constellation: 'Capricorne' },
  { image: 'images/M74-a.jpg', nom: 'Galaxie spirale', constellation: 'Poissons' },
  { image: 'images/M75-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M76-a.jpg', nom: 'Petite Dumbbell Nebula ', constellation: 'Persée' },
  { image: 'images/M77-a.jpg', nom: 'Galaxie du Lion ', constellation: 'Lion' },
  { image: 'images/M78-a.jpg', nom: 'Nébuleuse à émission', constellation: 'Licorne' },
  { image: 'images/M79-a.jpg', nom: 'Amas globulaire', constellation: 'Lièvre' },
  { image: 'images/M80-a.jpg', nom: 'Amas globulaire', constellation: 'Sagittaire' },
  { image: 'images/M81-a.jpg', nom: 'Galaxie de Bode', constellation: 'Grande Ourse' },
  { image: 'images/M82-a.jpg', nom: 'Galaxie du Cigare', constellation: 'Grande Ourse' },
  { image: 'images/M83-a.jpg', nom: 'Galaxie spirale', constellation: 'Hydre' },
  { image: 'images/M84-a.jpg', nom: 'Galaxie lenticulaire', constellation: 'Vierge' },
  { image: 'images/M85-a.jpg', nom: 'Galaxie lenticulaire', constellation: 'Vierge' },
  { image: 'images/M86-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge' },
  { image: 'images/M87-a.jpg', nom: 'Galaxie lenticulaire (Virgo A)', constellation: 'Vierge' },
  { image: 'images/M88-a.jpg', nom: 'Galaxie spirale', constellation: 'Vierge' },
  { image: 'images/M89-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge' },
  { image: 'images/M90-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Vierge' },
  { image: 'images/M91-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Grande Ourse' },
  { image: 'images/M92-a.jpg', nom: 'Amas globulaire d\'Hercule', constellation: 'Hercule' },
  { image: 'images/M93-a.jpg', nom: 'Amas ouvert', constellation: 'Poupe' },
  { image: 'images/M94-a.jpg', nom: 'Galaxie spirale', constellation: 'Chevelure de Bérénice' },
  { image: 'images/M95-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion' },
  { image: 'images/M96-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion' },
  { image: 'images/M97-a.jpg', nom: 'Nébuleuse du Hibou', constellation: 'Grande Ourse' },
  { image: 'images/M98-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion' },
  { image: 'images/M99-a.jpg', nom: 'La Toupie', constellation: 'Vierge' },
  { image: 'images/M100-a.jpg', nom: 'Galaxie de la Vierge ', constellation: 'Vierge' },
  { image: 'images/M101-a.jpg', nom: 'Galaxie Pinwheel', constellation: 'Grande Ourse' },
  { image: 'images/M102-a.jpg', nom: 'Galaxie du Fuseau', constellation: 'Dragon' },
  { image: 'images/M103-a.jpg', nom: 'Amas ouvert', constellation: 'Cassiopée' },
  { image: 'images/M104-a.jpg', nom: 'Galaxie du Sombréro', constellation: 'Vierge' },
  { image: 'images/M105-a.jpg', nom: 'Galaxie elliptique', constellation: 'Lion' },
  { image: 'images/M106-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Chiens de chasse' },
  { image: 'images/M107-a.jpg', nom: 'Amas globulaire', constellation: 'Ophiuchus' },
  { image: 'images/M108-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Grande Ourse' },
  { image: 'images/M109-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Grande Ourse' },
  { image: 'images/M110-a.jpg', nom: 'Galaxie elliptique', constellation: 'Andromède' },
  ];
