const objetsMessier = [
  { image: 'images/M11-a.jpg', nom: 'amas du Canard sauvage', constellation: 'Écu de Sobieski', saison : 'été', difficulté : ' Trés Facile ' },
 { image: 'images/M13-a.jpg', nom: 'amas d\'hercule', constellation: 'hercule', saison : 'été', difficulté : ' Trés Facile ' },
 { image: 'images/M22-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Trés Facile ' },
 { image: 'images/M35-a.jpg', nom: 'amas ouvert', constellation: 'Gémeaux', saison : 'hiver', difficulté : ' Trés Facile ' },
 { image: 'images/M42-a.jpg', nom: 'Grande Nébuleuse d\'Orion', constellation: 'Orion', saison : 'hiver', difficulté : ' Trés Facile ' },
 { image: 'images/M45-a.jpg', nom: 'Pléiades ', constellation: 'Taureau', saison : 'hiver', difficulté : ' Trés Facile ' },
 { image: 'images/M5-a.jpg', nom: 'amas globulaire', constellation: 'Serpent', saison : 'été', difficulté : ' Trés Facile' },
 { image: 'images/M30-a.jpg', nom: 'amas globulaire', constellation: 'Capricorne ', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M31-a.jpg', nom: 'Galaxie d\'andromède', constellation: 'andromède ', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M32-a.jpg', nom: 'Galaxie elliptique', constellation: 'andromède ', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M33-a.jpg', nom: 'Galaxie du Triangle', constellation: 'Triangle', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M34-a.jpg', nom: 'amas ouvert', constellation: 'Persée', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M39-a.jpg', nom: 'amas ouvert', constellation: 'Cygne', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M52-a.jpg', nom: 'amas ouvert', constellation: 'Cassiopée', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M103-a.jpg', nom: 'amas ouvert', constellation: 'Cassiopée', saison : 'automne', difficulté : ' Facile ' },
 { image: 'images/M6-a.jpg', nom: 'amas du papillon', constellation: 'Scorpion', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M7-a.jpg', nom: 'amas ouvert', constellation: 'Scorpion', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M16-a.jpg', nom: 'Nébuleuse de l\'aigle', constellation: 'Serpent', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M17-a.jpg', nom: 'Nébuleuse Oméga', constellation: 'Sagittaire', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M23-a.jpg', nom: 'amas ouvert', constellation: 'Sagittaire', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M25-a.jpg', nom: 'amas ouvert', constellation: 'Sagittaire', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M27-a.jpg', nom: 'Nébuleuse de l\'haltère (Dumbbell) ', constellation: 'Petit Renard', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M28-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M29-a.jpg', nom: 'amas ouvert', constellation: 'Cocher', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M57-b.jpg', nom: 'Nébuleuse de l\'anneau', constellation: 'Lyre', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M80-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M92-a.jpg', nom: 'amas globulaire d\'hercule', constellation: 'hercule', saison : 'été', difficulté : ' Facile ' },
 { image: 'images/M36-a.jpg', nom: 'amas ouvert', constellation: 'Gémeaux', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M37-a.jpg', nom: 'amas ouvert', constellation: 'Gémeaux', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M38-a.jpg', nom: 'amas ouvert ', constellation: 'Cocher', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M41-a.jpg', nom: 'amas ouvert', constellation: 'Grand Chien', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M43-a.jpg', nom: 'Nébuleuse de la Tête de Cheval', constellation: 'Orion', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M44-a.jpg', nom: 'amas ouvert ', constellation: 'Cancer', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M46-a.jpg', nom: 'amas ouvert', constellation: 'Petit Chien', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M47-a.jpg', nom: 'amas ouvert', constellation: 'Poupe', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M48-a.jpg', nom: 'amas ouvert', constellation: 'Poupe', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M50-a.jpg', nom: 'amas ouvert de la Licorne ', constellation: 'Licorne', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M67-a.jpg', nom: 'amas ouvert', constellation: 'Cancer', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M93-a.jpg', nom: 'amas ouvert', constellation: 'Poupe', saison : 'hiver', difficulté : ' Facile ' },
 { image: 'images/M40-a.jpg', nom: 'Étoile double (Winnecke 4)', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' Facile ' },
 { image: 'images/M53-a.jpg', nom: 'amas globulaire', constellation: 'Chevelure de Bérénice', saison : 'printemps', difficulté : ' Facile ' },
 { image: 'images/M66-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion', saison : 'printemps', difficulté : ' Facile ' },
 { image: 'images/M81-a.jpg', nom: 'Galaxie de Bode', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' Facile ' },
 { image: 'images/M82-a.jpg', nom: 'Galaxie du Cigare', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' Facile ' },
 { image: 'images/M104-a.jpg', nom: 'Galaxie du Sombréro', constellation: 'Vierge', saison : 'printemps', difficulté : ' Facile ' },
 { image: 'images/M2-a.jpg', nom: 'amas globulaire', constellation: 'hercule', saison : 'automne', difficulté : ' Facile' },
 { image: 'images/M3-a.jpg', nom: 'amas globulaire', constellation: 'Vierge', saison : 'printemps', difficulté : ' Facile' },
 { image: 'images/M76-a.jpg', nom: 'Petite dumbbell Nebula ', constellation: 'Persée', saison : 'automne', difficulté : ' Modéré ' },
 { image: 'images/M77-a.jpg', nom: 'Galaxie du Lion ', constellation: 'Lion', saison : 'automne', difficulté : ' Modéré ' },
 { image: 'images/M8-a.jpg', nom: 'Nébuleuse de la Lagune', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M9-a.jpg', nom: 'amas globulaire', constellation: 'Serpent', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M10-a.jpg', nom: 'amas globulaire', constellation: 'hercule', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M12-a.jpg', nom: 'amas globulaire', constellation: 'Ophiuchus', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M14-a.jpg', nom: 'amas globulaire', constellation: 'Ophiuchus', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M18-a.jpg', nom: 'amas ouvert', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M19-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M21-a.jpg', nom: 'amas ouvert', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M24-a.jpg', nom: 'Petit nuage du Sagittaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M26-a.jpg', nom: 'amas ouvert', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M54-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M56-a.jpg', nom: 'amas globulaire', constellation: 'Lyre', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M62-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M69-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M70-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M71-a.jpg', nom: 'amas globulaire', constellation: 'Flèche', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M72-a.jpg', nom: 'amas globulaire', constellation: 'Verseau', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M75-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' Modéré ' },
 { image: 'images/M78-a.jpg', nom: 'Nébuleuse à émission', constellation: 'Licorne', saison : 'hiver', difficulté : ' Modéré ' },
 { image: 'images/M79-a.jpg', nom: 'amas globulaire', constellation: 'Lièvre', saison : 'hiver', difficulté : ' Modéré ' },
 { image: 'images/M49-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M51-a.jpg', nom: 'Galaxie du Tourbillon ', constellation: 'Chiens de chasse', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M58-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M60-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M63-a.jpg', nom: 'Galaxie tournesol', constellation: 'Chiens de chasse', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M64-a.jpg', nom: 'Galaxie spirale', constellation: 'Chiens de chasse', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M65-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M84-a.jpg', nom: 'Galaxie lenticulaire', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M85-a.jpg', nom: 'Galaxie lenticulaire', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M86-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M87-a.jpg', nom: 'Galaxie lenticulaire (Virgo A)', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M88-a.jpg', nom: 'Galaxie spirale', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M89-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M94-a.jpg', nom: 'Galaxie spirale', constellation: 'Chevelure de Bérénice', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M96-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M105-a.jpg', nom: 'Galaxie elliptique', constellation: 'Lion', saison : 'printemps', difficulté : ' Modéré ' },
 { image: 'images/M1-a.jpg', nom: 'Nébuleuse du Crabe', constellation: 'Taureau', saison : 'hiver', difficulté : ' Modéré' },
 { image: 'images/M1-a.jpg', nom: 'Nébuleuse du Crabe', constellation: 'Taureau', saison : 'hiver', difficulté : ' Modéré' },
 { image: 'images/M110-a.jpg', nom: 'Galaxie elliptique', constellation: 'andromède', saison : 'automne', difficulté : ' difficile ' },
 { image: 'images/M55-a.jpg', nom: 'amas globulaire', constellation: 'Sagittaire', saison : 'été', difficulté : ' difficile ' },
 { image: 'images/M102-a.jpg', nom: 'Galaxie du Fuseau', constellation: 'Dragon', saison : 'été', difficulté : ' difficile ' },
 { image: 'images/M107-a.jpg', nom: 'amas globulaire', constellation: 'Ophiuchus', saison : 'été', difficulté : ' difficile ' },
 { image: 'images/M59-a.jpg', nom: 'Galaxie elliptique', constellation: 'Vierge', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M61-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Vierge', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M83-a.jpg', nom: 'Galaxie spirale', constellation: 'hydre', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M90-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Vierge', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M99-a.jpg', nom: 'La Toupie', constellation: 'Vierge', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M106-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Chiens de chasse', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M108-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M109-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M73-a.jpg', nom: 'Quatuor d\'étoiles ', constellation: 'Capricorne', saison : 'été', difficulté : ' difficile ' },
 { image: 'images/M95-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion', saison : 'printemps', difficulté : ' difficile ' },
 { image: 'images/M4-a.jpg', nom: 'amas globulaire', constellation: 'Scorpion', saison : 'été', difficulté : ' difficile' },
 { image: 'images/M74-a.jpg', nom: 'Galaxie spirale', constellation: 'Poissons', saison : 'automne', difficulté : ' Trés difficile ' },
 { image: 'images/M20-a.jpg', nom: 'Nébuleuse Trifide', constellation: 'Sagittaire', saison : 'été', difficulté : ' Trés difficile ' },
 { image: 'images/M68-a.jpg', nom: 'amas globulaire', constellation: 'Lion', saison : 'printemps', difficulté : ' Trés difficile ' },
 { image: 'images/M91-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' Trés difficile ' },
 { image: 'images/M97-a.jpg', nom: 'Nébuleuse du Hibou', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' Trés difficile ' },
 { image: 'images/M98-a.jpg', nom: 'Galaxie spirale barrée', constellation: 'Lion', saison : 'printemps', difficulté : ' Trés difficile ' },
 { image: 'images/M100-a.jpg', nom: 'Galaxie de la Vierge ', constellation: 'Vierge', saison : 'printemps', difficulté : ' Trés difficile ' },
 { image: 'images/M101-a.jpg', nom: 'Galaxie Pinwheel', constellation: 'Grande Ourse', saison : 'printemps', difficulté : ' Trés difficile ' },

];
