const donnees = [
{ titre:'NGC7662 ',constellation:'Andromède',image:'images/NGC7662-a.jpg', nom:'', type:' Nébuleuse planétaire',mag:'9'},
{ titre:'M32 ',constellation:'Andromède',image:'images/M32-a.jpg', nom:'', type:' Galaxie ',mag:' 8.2'},
{ titre:'M31 ',constellation:'Andromède',image:'images/M31-a.jpg', nom:'', type:' Galaxie ',mag:' 3.5'},
{ titre:'NGC752',constellation:'Andromède',image:'images/NGC752-a.jpg', nom:'', type:' Amas ouvert',mag:' 5.7'},
{ titre:'NGC281',constellation:'Cassiopée',image:'images/NGC281-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:'7'},
{ titre:'IC1805',constellation:'Cassiopée',image:'images/IC1805-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:' 6.5'},
{ titre:'IC1848',constellation:'Cassiopée',image:'images/IC1848-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:' 6.5'},
{ titre:'NGC185',constellation:'Cassiopée',image:'images/NGC185-a.jpg', nom:'', type:' Galaxie ',mag:' 9.2'},
{ titre:'NGC663',constellation:'Cassiopée',image:'images/NGC663-a.jpg', nom:'', type:' Amas ouvert',mag:' 7.1'},
{ titre:'NGC457',constellation:'Cassiopée',image:'images/NGC457-a.jpg', nom:'', type:' Amas ouvert',mag:' 6.4'},
{ titre:'NGC7789 ',constellation:'Cassiopée',image:'images/NGC7789-a.jpg', nom:'', type:' Amas ouvert',mag:' 6.7'},
{ titre:'NGC40 ',constellation:'Céphée ',image:'images/NGC40-a.jpg', nom:'', type:' Nébuleuse planétaire',mag:'11'},
{ titre:'NGC7129 ',constellation:'Céphée ',image:'images/NGC7129-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:'12'},
{ titre:'NGC2281 ',constellation:'Cocher ',image:'images/NGC2281-a.jpg', nom:'', type:' Amas ouvert',mag:' 5.4'},
{ titre:'M36 ',constellation:'Cocher ',image:'images/M36-a.jpg', nom:'', type:' Amas ouvert',mag:'6'},
{ titre:'NGC1907 ',constellation:'Cocher ',image:'images/NGC1907-a.jpg', nom:'', type:' Amas ouvert',mag:' 8.2'},
{ titre:'NGC1931 ',constellation:'Cocher ',image:'images/NGC1931-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:' 11.3 '},
{ titre:'IC5146',constellation:'Cygne',image:'images/IC5146-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:' 7.2'},
{ titre:'NGC2392 ',constellation:'Gémeaux',image:'images/NGC2392-a.jpg', nom:'', type:' Nébuleuse planétaire',mag:'10'},
{ titre:'NGC2158 ',constellation:'Gémeaux',image:'images/NGC2158-a.jpg', nom:'', type:' Amas ouvert',mag:' 8.6'},
{ titre:'NGC2841 ',constellation:'Grande Ourse ',image:'images/NGC2841-a.jpg', nom:'', type:' Galaxie',mag:' 9.3'},
{ titre:'M81 ',constellation:'Grande Ourse ',image:'images/M81-a.jpg', nom:'', type:' Galaxie',mag:' 6.9'},
{ titre:'NGC2244 ',constellation:'Licorne',image:'images/NGC2244-a.jpg', nom:'', type:' Amas ouvert',mag:' 4.8'},
{ titre:'NGC2264 ',constellation:'Licorne',image:'images/NGC2264-a.jpg', nom:'', type:' Amas+Nébuleuse',mag:' 3.9'},
{ titre:'M50 ',constellation:'Licorne',image:'images/M50-a.jpg', nom:'', type:' Amas ouvert',mag:' 5.9'},
{ titre:'NGC2903 ',constellation:'Lion ',image:'images/NGC2903-a.jpg', nom:'', type:' Galaxie',mag:' 8.9'},
{ titre:'M43 ',constellation:'Orion',image:'images/M43-a.jpg', nom:'', type:' Nébuleuse en réflection',mag:'9'},
{ titre:'NGC884',constellation:'Persée ',image:'images/NGC884-a.jpg', nom:'', type:' Amas ouvert',mag:'4'},
{ titre:'NGC1023 ',constellation:'Persée ',image:'images/NGC1023-a.jpg', nom:'', type:' Galaxie',mag:' 9.5'},

];
